import { ChatIcon, CloseIcon, FileIcon, ImageIcon, Logo, PlusIcon, ScanIcon, SparkleIcon } from './Icons'

const UNIT_LABEL = { page: 'Pages', section: 'Sections', image: 'Images' }

const TABS = [
  { id: 'chat', label: 'Ask questions', icon: ChatIcon },
  { id: 'summary', label: 'Summary', icon: SparkleIcon },
]

export default function Sidebar({ meta, view, onViewChange, onNewDocument, open, onClose }) {
  return (
    <>
      <div className={`scrim${open ? ' is-open' : ''}`} onClick={onClose} aria-hidden="true" />
      <aside className={`sidebar${open ? ' is-open' : ''}`} aria-label="Document panel">
        <div className="sidebar-top">
          <div className="brand">
            <Logo size={32} />
            <span>DocBot</span>
          </div>
          <button type="button" className="icon-btn sidebar-close" onClick={onClose} aria-label="Close menu">
            <CloseIcon size={18} />
          </button>
        </div>

        <button type="button" className="btn btn-primary btn-block" onClick={onNewDocument}>
          <PlusIcon size={16} /> New document
        </button>

        <nav className="tabs" aria-label="Mode">
          {TABS.map(({ id, label, icon: Icon }) => (
            <button
              key={id}
              type="button"
              className={`tab${view === id ? ' is-active' : ''}`}
              onClick={() => onViewChange(id)}
              aria-current={view === id ? 'page' : undefined}
            >
              <Icon size={18} /> {label}
            </button>
          ))}
        </nav>

        <div className="doc-card">
          <p className="doc-card-label">Current document</p>
          <div className="doc-card-name">
            <span className={`file-chip-icon kind-${meta.kind ?? 'pdf'}`}>
              {meta.kind === 'image' ? <ImageIcon size={18} /> : <FileIcon size={18} />}
            </span>
            <span title={meta.filename}>{meta.filename}</span>
          </div>
          <dl className="doc-stats">
            <div><dt>{UNIT_LABEL[meta.unit] ?? 'Pages'}</dt><dd>{meta.pages}</dd></div>
            <div><dt>Passages</dt><dd>{meta.chunks}</dd></div>
            <div><dt>Characters</dt><dd>{meta.characters.toLocaleString()}</dd></div>
          </dl>
          {meta.ocrPages > 0 && (
            <p className="ocr-note">
              <ScanIcon size={16} />
              <span>
                Text from {meta.ocrPages} {meta.kind === 'pdf' ? 'scanned page(s) or image(s)' : 'image(s)'} was
                read with OCR and may contain small errors.
              </span>
            </p>
          )}
          {meta.ocrSkipped > 0 && (
            <p className="ocr-note is-warn" role="status">
              <ScanIcon size={16} />
              <span>{meta.ocrSkipped} more page(s)/image(s) weren’t OCR’d because of the per-upload limit.</span>
            </p>
          )}
        </div>

        <p className="sidebar-foot">Answers are generated by Claude Sonnet 5.5 from your document. Check important facts against the source pages.</p>
      </aside>
    </>
  )
}
